### ISSUE TITLE
convert params when "use" is used

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/generator#10]
PHP file:

```
<?php

use foo\bar;

/**
 * @return bar
 */
function hello() {
    ...
}
```

stubs:
```
<?php
/**
 * @return bar
 */
function hello() {
}
```

Currently, the stubs just remove all "use". This will cause errors for undefined class "bar".
Would it be possible to automatically just replace all param/return with their corresponding "use" class?
So the stubs would actually be:

```
<?php
/**
 * @return foo\bar
 */
function hello() {
}
```

**Comment by szepeviktor** [comment]
Hello @kkmuffme!

1. This is fork for fixing problems
2. WordPress source code does not contain `use`
3. You should use FQCN in doc blocks and exceptions

This is all I have :(

**Comment by kkmuffme** [comment]
1. 
https://github.com/GiacoCorsiglia/php-stubs-generator
>You should use the fork at [php-stubs/generator](https://github.com/php-stubs/generator), which is thanks to [@szepeviktor](https://github.com/szepeviktor).

:sweat:
What do you recommend to get support for `use` added? I'd contribute if I could get some guidance.

2. I use this for other libraries, not WordPress, where `use` is used

3. but phpstan correctly infers the class if `use` is there even when not using FQCN but just `bar` (in the example above).
Also this issue is with third party code only unfortunately (Google libs for example all use `use` without FQCN in phpdoc)

**Comment by szepeviktor** [comment]
I think you should create a new NodeVisitor.
e.g. https://github.com/php-stubs/wordpress-stubs/blob/master/visitor.php

1. Remember imported classes
2. Change class name to FQCN at every `use`

(I'm not a developer, I have to google every line of code)

**Comment by kkmuffme** [comment]
Would you accept a PR for this?

**Comment by szepeviktor** [comment]
Yes. See for example #5

**Comment by justlevine** [comment]
@kkmuffme were you able to figure out a solution? I'm running into the same trouble with [WPGraphQL Stubs](https://github.com/AxeWP/wp-graphql-stubs), but I've been struggling to figure out the correct syntax for `visitor.php`... 🤔

**Comment by szepeviktor** [comment]
> https://github.com/AxeWP/wp-graphql-stubs

What a project!
