### ISSUE TITLE
Finder ->append failing silently

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/generator#11]
an issue you encountered yourself already here https://github.com/php-stubs/woocommerce-stubs/blob/master/finder.php

Symfony `->append( '/path/to/file.php' )` should work fine
but when doing this the generator fails silently.

Instead one has to workaround with:

```
->append(
        \StubsGenerator\Finder::create()
            ->in(['source/woocommerce'])
            ->files()
            ->depth('< 1')
            ->path('woocommerce.php')
    )
```

which is a pain if you have an array of files you want to append

**Comment by szepeviktor** [comment]
Hello @kkmuffme!
This repo is for solving a fixed set of problmes upstream.

Please see https://github.com/symfony/finder/blob/5.4/Finder.php#L170 and solve it yourself.
