### ISSUE TITLE
How to override phpdocs

### ISSUE THREAD

**Issue by criskell** [php-stubs/generator#23]
When I am generating the stub, I would like to modify the PHPDoc of a specific method of a specific class.

Would it be possible?

**Comment by szepeviktor** [comment]
Thank you for asking @criskell!

👋🏻

You may modify the implementation in WP stubs.
https://github.com/php-stubs/wordpress-stubs/blob/9da4e91a9dce4faf64f3f943f523c624626b59a5/visitor.php#L236

**Comment by szepeviktor** [comment]
`sed` is a simpler alternative.

https://github.com/php-stubs/wordpress-stubs/blob/9da4e91a9dce4faf64f3f943f523c624626b59a5/generate.sh#L37-L70

**Comment by criskell** [comment]
I got it using sed's idea, thanks!

maybe it would be nice to have a functionality to merge stubs files?

so I wouldn't need to use sed, I would only use PHP

**Comment by szepeviktor** [comment]
It is very easy. Add those changes **before** generating stubs.
The generator can handle duplicated function.
