### ISSUE TITLE
Psalm has similar generator

### ISSUE THREAD

**Issue by WinterSilence** [php-stubs/generator#6]
I don't want to upset package devs, but Psalm has a similar generator for a long time: https://psalm.dev/docs/running_psalm/plugins/authoring_plugins/  It would be great to combine packages.

**Comment by szepeviktor** [comment]
Thank you very much!

I'm a @phpstan guy developing extensions for Laravel and WordPress. (for technical reasons)
Psalm - AFAIK - lacks Symfony finder to pick what files should be included in stubs generation.

What problem would you like to solve?

**Comment by kkmuffme** [comment]
This is a gazillion times better than psalm's built-in one, because it can be automated and customized way better thx to the Symfony finder

**Comment by WinterSilence** [comment]
@szepeviktor @kkmuffme 
> It would be great to combine packages.

**Comment by szepeviktor** [comment]
I don't dare to make a public statement about `vimeo/pslam`.
Once I had done it on Twitter, you don't want to to know the outcome!
