### ISSUE TITLE
Cannot create stubs for plugin

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/generator#7]
Worked great so far, however for 1 plugin I cannot generate the stubs and get PHP notices.
Maybe I'm doing something wrong?

Plugin: https://wordpress.org/plugins/woocommerce-paypal-payments/

>Trying to access array offset on value of type null

in php-stubs/generator/src/NodeVisitor.php on line 169

I'm using `->notPath( '/Test/' )` to exclude tests (there are some other errors otherwise)

Additionally generate-stubs fails silently (and with result code 0) which may be an issue that needs to be investigated separately (to get a proper error message/exit code 1)

**Comment by szepeviktor** [comment]
Hello @kkmuffme!

Try debugging around #4

**Comment by szepeviktor** [comment]
No!
Run this command.
```
$ vendor/bin/generate-stubs --functions --classes --interfaces --traits --out=woocommerce-paypal-payments-stubs.php -- woocommerce-paypal-payments/src/ woocommerce-paypal-payments/modules/*/src/

PHP Stubs Generator
===================


 [OK] Stubs written to /home/viktor/src/a/woocommerce-paypal-payments-stubs.php


 ----------- --------- ------------ -------- ----------- ---------
  functions   classes   interfaces   traits   constants   globals
 ----------- --------- ------------ -------- ----------- ---------
  0           166       7            7        0           0
 ----------- --------- ------------ -------- ----------- ---------
```

**Comment by kkmuffme** [comment]
so basically ignoring the vendor directory?
Should "vendor" be generally ignored when generating stubs?

**Comment by szepeviktor** [comment]
> so basically ignoring the vendor directory?

Nooo! :) Vendor code is autoloaded so simply require those packages.

**Comment by kkmuffme** [comment]
The plugin comes with "vendor", I downloaded this from WP. This isn't installed with composer.

>vendor/bin/generate-stubs --functions --classes --interfaces --traits --out=woocommerce-paypal-payments-stubs.php -- woocommerce-paypal-payments/src/ woocommerce-paypal-payments/modules/*/src/

is like setting `->notPath( '/vendor/' )` isn't it?

**Comment by szepeviktor** [comment]
> is like setting `->notPath( '/vendor/' )` isn't it?

You may do this in a separate `finder.php` but command line is enough in this case.

**Comment by szepeviktor** [comment]
Be aware that this plugin is subpar quality ⚠️

**Comment by kkmuffme** [comment]
When I exclude vendor directory, it will not include those vendor things in the stubs (even though there is a autoload.php in vendor directory)
Isn't this an issue? (sorry I'm new to generating my own stubs)

>Be aware that this plugin is subpar quality ⚠️

Thanks I know, just want to stub it as it's official from WooCommerce and may replace the native Paypal method (so I want to be prepared)

**Comment by szepeviktor** [comment]
Stubs are for non-OOP code.
If WordPress would be OOP you would not need stubs :)

Include those packages using Composer!

**Comment by kkmuffme** [comment]
>Include those packages using Composer!

Include where?
I put them in psalm config <stubs>
There's nothing getting autoloaded, since it's not composer I am running with

**Comment by szepeviktor** [comment]
I'm sorry. I'm a PHPStan guy. Psalm is very far away from me.

![kép](https://user-images.githubusercontent.com/952007/148569679-9fa24f69-a682-4288-8ffe-d397daff34b6.png)
https://actd.nl/2021/01/06/understanding-psalm-autoloader/
