### ISSUE TITLE
Undefined property: PhpParser\Node\Expr\BinaryOp\Concat::$value

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/generator#8]
when using https://github.com/php-stubs/woocommerce-stubs/blob/master/finder.php I get a PHP error:

Undefined property: PhpParser\Node\Expr\BinaryOp\Concat::$value
File: vendor/php-stubs/generator/src/NodeVisitor.php on line 378

just wanted to ask if you want to fix (workaround?) it, or if this should be reported upstream?

**Comment by szepeviktor** [comment]
- WC 6.0 has problems
- wc-stubs uses the old generator https://github.com/php-stubs/woocommerce-stubs/blob/master/composer.json#L17

**Comment by szepeviktor** [comment]
BTW Including constants in stubs may be not necessary.
