### ISSUE TITLE
Class missing in stubs

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/generator#9]
Package installed with composer: abraham/twitteroauth
(I need the stubs as I'm doing something like you do with the WP stubs which do not use composer, so I need stubs)

`generate-stubs --force --functions --classes --interfaces --traits --out="a.php" --no-interaction twitter`
(package is installed in twitter folder)

It generates the stubs (10 classes), but stubs for `class TwitterOAuth extends Config` are missing.
But e.g. `class TwitterOAuthException extends \Exception` and all other classes are there (total 11 classes, but only 10 have stubs created).

Is this a bug or is there something I'm doing wrong?

**Comment by szepeviktor** [comment]
Hello @kkmuffme!
Try to generate from that specific file.

It is very easy to debug this project.

**Comment by kkmuffme** [comment]
If I run it for that file only, there are no errors either (but no stubs generated) it even says "OK":

```
PHP Stubs Generator
===================


 [OK] Stubs written to /some/path/a.php


 ----------- --------- ------------ -------- ----------- ---------
  functions   classes   interfaces   traits   constants   globals
 ----------- --------- ------------ -------- ----------- ---------
  0           0         0            0        0           0
 ----------- --------- ------------ -------- ----------- ---------
 ```
 
 and the output file contains only:
 
```
<?php

```

**Comment by szepeviktor** [comment]
Try debugging in this try/catch block
https://github.com/php-stubs/generator/blob/53c2cbb0ab3049d73d4490d47c9f2f9028580ef8/src/StubsGenerator.php#L133
Please see #4

**Comment by dingo-d** [comment]
I'm also experiencing the same issue. When manually trying to generate the stubs from the command line I get the correct number of stubs recognized, but when I check the file, it's empty.

<img width="1368" alt="image" src="https://user-images.githubusercontent.com/8638515/168802628-3ec43e7a-2ea3-4580-8672-b9fb92bdffd5.png">

When I don't specify `out` parameter I don't get anything out.

No error is thrown.

I var dumped the visitor in the `StubsGenerator.php`, and I can see the correct class and traits mentioned, the `$unparsed` variable is empty, which is ok.

Not sure why nothing is getting parsed out.

**Comment by dingo-d** [comment]
My PHP parsing is not strong, so I'll wait for a fix, but when you'll have something feel free to ping me to test it 👍🏼

**Comment by szepeviktor** [comment]
```
$ vendor/bin/generate-stubs --functions --classes --interfaces --traits src/Helpers/ | wc -l
909
```

**Comment by herndlm** [comment]
Would a new config switch for that behaviour (include "existing" things) be useful? Maybe such issues can than be avoided

**Comment by szepeviktor** [comment]
I'm sorry, Martin! This is a highly dangerous ⚡ fork for php-stub organization stubs only.
Without php-stubs this would be https://github.com/GiacoCorsiglia/php-stubs-generator
